![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

# Einleitung
Herzlich willkommen zur Einführung in Pandas! In der kommenden Lektion wirst du die Grundlagen von **Pandas** kennenlernen. Ziel ist es, dich mit effizienten Datenverarbeitungs- und Analysewerkzeugen vertraut zu machen, die dir in vielen Datenprojekten hilfreich sein werden.

Stell dir vor, du arbeitest in einem Team, das Markt-, Verkaufs- und Lieferantendaten analysiert, um wichtige Geschäftsentscheidungen zu treffen. Deine Aufgabe ist es, die Daten effizient zu importieren, zu analysieren und relevante Ergebnisse zu exportieren.


# Grundlagen von Pandas

Pandas ist eine beliebte Open-Source-Programmbibliothek, die speziell für die Datenanalyse und Datenmanipulation entwickelt wurde. Man kann sich Pandas wie eine mächtige, programmierbare Version von Excel vorstellen, die auch sehr große Datenmengen extrem schnell verarbeiten kann.

## 1. Das Pandas Dataframe
Pandas bietet verschiedene vorgefertigte Datenstrukturen, um uns das Arbeiten mit Daten unterschiedlichster Struktur so einfach wie möglich zu machen. Abhängig von der Struktur der Daten gibt es hierfür entweder die sogenannten *Series* oder die *Dataframes*.

Eine Pandas Series ist eine eindimensionale, beschriftete Liste, deren Felder quasi jeden Datentyp (Int, Float, String, Python Objects,...) annehmen kann. Sie ist vergleichbar mit einer einzelnen Spalte in einer Tabelle. Mithilfe von Indizes können wir sehr leicht auf die einzelnen Datenfelder in der Series zugreifen.

Für unsere Zwecke nutzen wir jedoch zu 99% das Pandas-Dataframe. Es ist quasi die zweidimensionale Version einer Series und erlaubt uns, jegliche Datentypen in einer zweidimensionalen, tabellarischen Datenstruktur unterzubringen, mit der sich sehr komfortabel weiterarbeiten lässt.

## 2. Daten laden

Erstmal wollen wir die **CSV-Dateien als Pandas-DataFrames** importieren.
- market_data
- sales_data

In [1]:
# Pandas Bibliothek importieren
import pandas as pd

# Dateien importieren
market_data = pd.read_csv('project_data/market_data.csv')
sales_data = pd.read_csv('project_data/sales_data.csv')


## 3. Untersuchung der DataFrame-Struktur

Nach dem Laden mehrerer **CSV-Dateien als Pandas-DataFrames**, sollen folgende **Strukturelemente** untersucht werden:  
- **Spaltennamen**  
- **Datentypen**  
- **Anzahl der Zeilen und Spalten**

In [5]:
# Überprüfung der geladenen DataFrames
print(market_data.describe())
print("###############")
market_data.info()
print("###############")
market_data.head(10)

       Preis pro Einheit (EUR)  Verkaufte Menge
count             10000.000000     10000.000000
mean                  0.621864       124.754900
std                   0.213824        43.378278
min                   0.270000        50.000000
25%                   0.450000        87.000000
50%                   0.630000       125.000000
75%                   0.750000       162.000000
max                   1.100000       200.000000
###############
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Produkt                  10000 non-null  str
 1   Preis pro Einheit (EUR)  10000 non-null  float64
 2   Verkaufte Menge          10000 non-null  int64
 3   Verfallsdatum            10000 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 470.2 KB
###############

   Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum
0  Zitrone                     0.58               76    2025-01-13
1   Banane                     0.28               55    2025-01-18
2   Banane                     0.30              186    2025-02-03
3    Gurke                     0.85              184    2025-01-26
4   Tomate                     0.74              114    2025-01-25
5   Tomate                     0.65              130    2025-01-25
6    Apfel                     0.51              115    2025-01-30
7  Zitrone                     0.54              197    2025-01-18
8    Gurke                     0.78              190    2025-01-25
9  Zitrone                     0.66              170    2025-01-27

Wir haben nun also einen ersten Eindruck von den Daten und ihrer Struktur erhalten - offenbar handelt es sich um Inventar-Daten eines Supermarktes oder anderen Geschäfts, das Obst und Gemüse verkauft.
Was aber, wenn wir einen genaueren Blick in die Daten werfen möchten? Hierfür bietet die Pandas-Bibliothek mehrere Möglichkeiten:


Wenn wir nur eine spezifische Spalte auswählen möchten, können wir wie bei Python-Listen eckige Klammern und einen Index benutzen. praktisch ist hierbei, dass wir den Namen einer Spalte als Index benutzen können.

In [6]:
print(market_data['Produkt'])

0       Zitrone
1        Banane
2        Banane
3         Gurke
4        Tomate
         ...
9995     Orange
9996      Gurke
9997    Zitrone
9998    Paprika
9999      Gurke
Name: Produkt, Length: 10000, dtype: str

Wir können mit ebenjener Syntax auch Listen als Argument übergeben, um mehrere Spalten auszuwählen:

In [7]:
print(market_data[['Produkt', 'Verkaufte Menge']])

      Produkt  Verkaufte Menge
0     Zitrone               76
1      Banane               55
2      Banane              186
3       Gurke              184
4      Tomate              114
...       ...              ...
9995   Orange              162
9996    Gurke              191
9997  Zitrone              118
9998  Paprika              103
9999    Gurke              198

[10000 rows x 2 columns]

Möchten wir stattdessen auf spezifische *Zeilen* zugreifen, können wir `loc[]` oder `iloc[]` benutzen:

In [15]:
print(market_data.iloc[0], "\n")

print(market_data.loc[market_data['Produkt'] == 'Zitrone'])

Produkt                       Zitrone
Preis pro Einheit (EUR)          0.58
Verkaufte Menge                    76
Verfallsdatum              2025-01-13
Name: 0, dtype: object

      Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum
0     Zitrone                     0.58               76    2025-01-13
7     Zitrone                     0.54              197    2025-01-18
9     Zitrone                     0.66              170    2025-01-27
14    Zitrone                     0.58              121    2025-01-29
17    Zitrone                     0.61              112    2025-01-27
...       ...                      ...              ...           ...
9964  Zitrone                     0.55              129    2025-01-18
9969  Zitrone                     0.60              163    2025-01-14
9982  Zitrone                     0.65               58    2025-02-02
9994  Zitrone                     0.60              106    2025-01-24
9997  Zitrone                     0.58              118    2025-01-31

[1246 rows x 4 columns]

Zuletzt stellt sich noch die Frage: was, wenn ich *Bereiche* statt einzelner Spalten/Zeilen auswählen möchte?
Wir erinnern uns (hoffentlich) an Python Listen, und wie man es dort umgesetzt hat.

In [25]:
#print(market_data.iloc[1:20:1, 0:4:1])
# [ZeileStart:ZeileStop,ZeileStep, SpalteStart:SpalteStop:SpalteStep]
display(market_data.loc[1:5, "Produkt":"Preis pro Einheit (EUR)"])

  Produkt  Preis pro Einheit (EUR)
1  Banane                     0.28
2  Banane                     0.30
3   Gurke                     0.85
4  Tomate                     0.74
5  Tomate                     0.65

## 4. Weitere Dataframe Funktionen

Wir können die Syntax für Indexing auch nutzen, um nur Felder zu erhalten, die eine bestimmte Kondition erfüllen

In [27]:
filtered_market = market_data[market_data['Preis pro Einheit (EUR)'] < 0.50]
print(filtered_market) # Printed die Daten als Text (trotzdem in Tabellenform)
display(filtered_market) # Stellt die Daten als Tabelle dar

      Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum
1      Banane                     0.28               55    2025-01-18
2      Banane                     0.30              186    2025-02-03
13    Karotte                     0.41               62    2025-02-05
16    Karotte                     0.40               88    2025-02-04
19     Banane                     0.30              137    2025-01-25
...       ...                      ...              ...           ...
9979    Apfel                     0.49              132    2025-01-22
9980  Karotte                     0.42              143    2025-01-29
9984   Banane                     0.33              145    2025-01-25
9986  Karotte                     0.40               91    2025-01-25
9990  Karotte                     0.36              180    2025-01-23

[3047 rows x 4 columns]

      Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum
1      Banane                     0.28               55    2025-01-18
2      Banane                     0.30              186    2025-02-03
13    Karotte                     0.41               62    2025-02-05
16    Karotte                     0.40               88    2025-02-04
19     Banane                     0.30              137    2025-01-25
...       ...                      ...              ...           ...
9979    Apfel                     0.49              132    2025-01-22
9980  Karotte                     0.42              143    2025-01-29
9984   Banane                     0.33              145    2025-01-25
9986  Karotte                     0.40               91    2025-01-25
9990  Karotte                     0.36              180    2025-01-23

[3047 rows x 4 columns]

Wir können ebenfalls Sortierungen durchführen, um unsere Dataframes in eine übersichtlichere Form zu bringen.

In [34]:
sorted_market = market_data.sort_values(by="Preis pro Einheit (EUR)", ascending=False)
display(sorted_market.head(10))

      Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum
9800  Paprika                      1.1              166    2025-01-15
1888  Paprika                      1.1               53    2025-01-12
1487  Paprika                      1.1              129    2025-02-08
7172  Paprika                      1.1               93    2025-01-23
9612  Paprika                      1.1              165    2025-02-02
688   Paprika                      1.1               84    2025-01-16
9576  Paprika                      1.1               86    2025-02-03
6289  Paprika                      1.1               83    2025-01-16
490   Paprika                      1.1               67    2025-01-30
5931  Paprika                      1.1               74    2025-01-19

Besonders hilfreich ist auch die Möglichkeit, gesamte (numerische) Spalten miteinander zu verrechnen. Wir können z.B. Spalten Wert-für-Wert miteinander multiplizieren und ohne Zwischenschritt eine neue Spalte it den Ergebnissen erzeugen!

In [35]:
market_data['Gesamtwert'] = market_data['Preis pro Einheit (EUR)'] * market_data['Verkaufte Menge']
print(market_data.head())

   Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum  Gesamtwert
0  Zitrone                     0.58               76    2025-01-13       44.08
1   Banane                     0.28               55    2025-01-18       15.40
2   Banane                     0.30              186    2025-02-03       55.80
3    Gurke                     0.85              184    2025-01-26      156.40
4   Tomate                     0.74              114    2025-01-25       84.36


Als nächstes wollen wir die Produkte finden, deren Verfallsdatum bereits überschritten wurde. Wie können wir das umsetzen?

In [37]:
abgelaufen = market_data[market_data['Verfallsdatum'] < "2025-01-15"]
abgelaufen.sort_values(by="Verfallsdatum")

,Produkt,Preis pro Einheit (EUR),Verkaufte Menge,Verfallsdatum,Gesamtwert
23,Karotte,0.39,150,2025-01-12,58.50
37,Zitrone,0.63,110,2025-01-12,69.30
90,Gurke,0.79,110,2025-01-12,86.90
92,Paprika,0.95,57,2025-01-12,54.15
111,Tomate,0.73,121,2025-01-12,88.33
...,...,...,...,...,...
9833,Banane,0.32,131,2025-01-14,41.92
9848,Zitrone,0.60,120,2025-01-14,72.00
9907,Paprika,0.99,124,2025-01-14,122.76
9947,Paprika,1.04,177,2025-01-14,184.08
9969,Zitrone,0.60,163,2025-01-14,97.80

Wir können auch Felder mit spezifischen Werten filtern.

In [42]:
apfel_banane = market_data[(market_data["Produkt"] == "Apfel") | (market_data["Produkt"] == "Banane")]
apfel_banane.head(10)

   Produkt  Preis pro Einheit (EUR)  Verkaufte Menge Verfallsdatum  Gesamtwert
1   Banane                     0.28               55    2025-01-18       15.40
2   Banane                     0.30              186    2025-02-03       55.80
6    Apfel                     0.51              115    2025-01-30       58.65
11   Apfel                     0.54              198    2025-02-08      106.92
19  Banane                     0.30              137    2025-01-25       41.10
20  Banane                     0.31              169    2025-01-29       52.39
33  Banane                     0.29              134    2025-01-21       38.86
40  Banane                     0.30              109    2025-01-18       32.70
56  Banane                     0.31               89    2025-02-11       27.59
58  Banane                     0.29               88    2025-01-21       25.52

---

## Sales Data Aufgaben

Die folgenden Aufgaben können wir nun gemeinsam lösen.

Zeige alle **Verkäufe**, die am **01. Januar 2025** stattgefunden haben.

Sortiere die Verkäufe nach den Einnahmen (absteigend) und zeige die Top 3.

Berechne den **Preis pro Einheit** als **`Einnahmen (EUR) / verkaufte Menge`** und füge ihn als neue Spalte hinzu.